import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Figtree } from "next/font/google";
import QueryProvider from "@/components/QueryProvider";

// import { QueryClient, QueryClientProvider } from "react-query";

const figtree = Figtree({
	subsets: ["latin"],
	variable: "--font-figtree",
	weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
	title: "Umoja International",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${figtree.className} antialiased bg-gray-50`}>
				<QueryProvider>
					<Navbar />

					<main className="max-w-screen-3xl mx-auto min-h-screen py-20">
						{children}
					</main>

					<Footer />
				</QueryProvider>
			</body>
		</html>
	);
}
